name: Bug 反馈
description: 创建一个报告帮助我们改进 RemoteMC-Core
title: "[Bug]: "
labels: ["type:bug"]
assignees: Cubik65536

body:
  - type: markdown
    attributes:
      value: |
        感谢您参与反馈问题。
        
        > ### 重要！ :warning:
        > 
        > issue 专为报告问题以及请求新功能而设。这意味着我们不会在此处接受任何关于使用的问题。
        > 如果您打开的 issue 不符合要求，它将被关闭。
        >
        > 对于使用上的问题，请参考以下资源：
        > * 在[QQ 群聊](https://qm.qq.com/cgi-bin/qm/qr?k=E0krQBZ1p3RzAhAjktAa9v-Cpf6zQaX8&authKey=QnnlGNdVKY5I4ZRc2p29Eefa08vUOV6sGk/uIT9ZJA/dkmnibGkq9ukb7ilNvOYc&noverify=0)内搜索或提问

  - type: checkboxes
    id: confirm
    attributes:
      label: "请选择："
      options:
        - label: 我正在着手修复这个问题
          required: false

  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: 问题描述
      description: |
        清晰简洁的描述您遇到的错误。
        请告诉我们它是构建时错误还是运行时错误。
      value: |
        当我执行 <X> 时，会发生 <Y> 并且我看到以下错误消息：
        
        ```
        <错误信息>
        ```
        
        预期行为：
        
        当我执行 <X> 时，应该发生 <Z>。
      render: Markdown

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: 重现
      description: |
        添加用于重现行为的命令或采取的步骤。
        包括链接、参考资料以及其他任何可以帮助我们了解您遇到的问题的内容。
      value: |
        1. 从 Release 页面下载 jar
        2. 将配置文件的 '...' 设置为 '...'
        3. 使用 `java -jar` 运行 jar
        4. 看到错误
      render: Markdown

  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出（如果有）
      description: |
        请复制并粘贴任何相关的日志输出。您的内容会自动被格式化为代码。
        粘贴详细日志时，请确保删除所有敏感信息。
      render: Shell

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: 环境
      description: |
        示例：
          - **操作系统**：macOS Monterey 12.3
          - **Java 版本**：Temurin-17.0.1+12
          - **RemoteMC-Core 版本 (或 commit 号)**：0.2.1 Beta (或 bd259a6)
          - **RemoteMC-MCDR 版本 (或 commit 号)**：0.1.0 Beta (或 20081cd)
      value: |
        - **操作系统**：
        - **Java 版本：**：
        - **RemoteMC-Core 版本 (或 commit 号)：**：
        - **RemoteMC-MCDR 版本 (或 commit 号)：**：
      render: Markdown

  - type: markdown
    attributes:
      value: |
        ---------
        
        在您提交本 issue 之前，请确认以下内容：
        
        **1. 本问题是否已经被反馈过了？**
        
        请确认是否已经有 issue 反馈过了本问题。
        
        **2. 确认您提交的是错误报告**
        
        请确认您提交的是错误报告，而不是使用上的问题。
        
        **3. 确认本错误仍然存在于最新版本的 RemoteMC-Core 中**
        
        请确认本错误仍然存在于最新版本（或提交）的 RemoteMC-Core 中。
        
        ---------
  - type: checkboxes
    id: terms
    attributes:
      label: 请确认以下条款
      options:
        - label: 我已经查看了[已有 issue](https://github.com/iXORTech/RemoteMC-Core/issues) 并确定我提交的问题并没有重复
          required: true
        - label: 本 issue 是 bug 反馈
          required: true
        - label: 本 bug 在最新版本中仍存在
          required: true
