blank_issues_enabled: false
contact_links:
  - name: Search or ask in QQ Group | 在 QQ 群聊中搜索或提问
    url: https://qm.qq.com/cgi-bin/qm/qr?k=E0krQBZ1p3RzAhAjktAa9v-Cpf6zQaX8&authKey=QnnlGNdVKY5I4ZRc2p29Eefa08vUOV6sGk/uIT9ZJA/dkmnibGkq9ukb7ilNvOYc&noverify=0
    about: Ask questions and discuss with iXORTech engineers and other users in real-time. | 在 QQ 群聊中搜索或提问，与 iXORTech 工程师和其他用户进行实时交流。
